name: Auto Fix
on:
  pull_request:
    branches: [ main ]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Auto code review
      run: |
        curl -X GET https://6433b372582420e23169798a.mockapi.io/api/v1/smartcodereview/review
    - name: Lint & fix
      run: npx eslint . --fix --ext .js
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.AUTOFIX }}
        base: ${{ github.head_ref }}
        branch: ${{ github.head_ref }}-autofix
        reviewers: ${{ github.actor }}
        labels: autofix
        delete-branch: true
        title: "Autofix for branch ${{ github.head_ref }}"
        body: |
            Automated PR to improve codestyle
            - Base PR ${{github.event.pull_request.url}}
